# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.5"
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.33.100"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "lamp-stack"
        vb.memory = "1024"
    end
    config.vm.provision :shell, path: "Vagrant.bootstrap.sh"
    config.vm.synced_folder "./apache-server", "/vagrant", type: "rsync",
        rsync__exclude: ".git/"
end
